import type { Flight, Route, SeatUtilization, PricingRecommendation, Analytics } from "./types"

export const mockFlights: Flight[] = [
  {
    id: "1",
    flightNumber: "AA101",
    airline: "South African Airways",
    origin: "Entebbe International Airport",
    destination: "Jomo Kenyatta International Airport",
    departureTime: "08:00",
    arrivalTime: "11:30",
    aircraft: "Airbus A330-300",
    totalSeats: 297,
    bookedSeats: 210,
    price: 299,
    status: "scheduled",
    date: "2025-01-15",
  },
  {
    id: "2",
    flightNumber: "DL205",
    airline: "Delta Airlines",
    origin: "ATL",
    destination: "MIA",
    departureTime: "14:15",
    arrivalTime: "16:45",
    aircraft: "Airbus A320",
    totalSeats: 150,
    bookedSeats: 89,
    price: 189,
    status: "scheduled",
    date: "2025-01-15",
  },
  {
    id: "3",
    flightNumber: "UA456",
    airline: "United Airlines",
    origin: "ORD",
    destination: "SFO",
    departureTime: "19:30",
    arrivalTime: "22:15",
    aircraft: "Boeing 777",
    totalSeats: 300,
    bookedSeats: 145,
    price: 349,
    status: "scheduled",
    date: "2025-01-15",
  },
  {
    id: "4",
    flightNumber: "SW789",
    airline: "Southwest Airlines",
    origin: "DEN",
    destination: "PHX",
    departureTime: "12:00",
    arrivalTime: "13:20",
    aircraft: "Boeing 737",
    totalSeats: 175,
    bookedSeats: 165,
    price: 129,
    status: "scheduled",
    date: "2025-01-15",
  },
]

export const mockRoutes: Route[] = [
  {
    id: "1",
    origin: "JFK",
    destination: "LAX",
    distance: 2475,
    averageLoadFactor: 78,
    frequency: 14,
    seasonality: "high",
    profitability: 85,
  },
  {
    id: "2",
    origin: "ATL",
    destination: "MIA",
    distance: 594,
    averageLoadFactor: 65,
    frequency: 21,
    seasonality: "medium",
    profitability: 72,
  },
  {
    id: "3",
    origin: "ORD",
    destination: "SFO",
    distance: 1846,
    averageLoadFactor: 52,
    frequency: 10,
    seasonality: "low",
    profitability: 45,
  },
]

export const mockSeatUtilization: SeatUtilization[] = [
  {
    flightId: "1",
    predictedOccupancy: 67,
    confidence: 85,
    emptySeats: 60,
    riskLevel: "medium",
    recommendations: ["Offer community pricing", "Consider route timing adjustment"],
  },
  {
    flightId: "2",
    predictedOccupancy: 59,
    confidence: 78,
    emptySeats: 61,
    riskLevel: "high",
    recommendations: ["Implement dynamic pricing", "Target local community outreach"],
  },
  {
    flightId: "3",
    predictedOccupancy: 48,
    confidence: 92,
    emptySeats: 155,
    riskLevel: "high",
    recommendations: ["Consider flight consolidation", "Aggressive community pricing"],
  },
]

export const mockPricingRecommendations: PricingRecommendation[] = [
  {
    flightId: "1",
    currentPrice: 299,
    recommendedPrice: 199,
    discount: 33,
    targetAudience: "community",
    urgency: "medium",
  },
  {
    flightId: "2",
    currentPrice: 189,
    recommendedPrice: 129,
    discount: 32,
    targetAudience: "community",
    urgency: "high",
  },
  {
    flightId: "3",
    currentPrice: 349,
    recommendedPrice: 179,
    discount: 49,
    targetAudience: "community",
    urgency: "high",
  },
]

export const mockAnalytics: Analytics = {
  totalFlights: 156,
  averageLoadFactor: 68,
  emptySeatsToday: 2847,
  revenueOpportunity: 284700,
  routesAtRisk: 12,
  communityBookings: 89,
}
