import type { Flight, Route, SeatUtilization, PricingRecommendation, Analytics } from "./types"

export const mockFlights: Flight[] = [
  {
    id: "1",
    flightNumber: "SAA190",
    airline: "South African Airways",
    origin: "Entebbe International Airport",
    destination: "Jomo Kenyatta International Airport",
    departureTime: "07:45",
    arrivalTime: "09:30",
    aircraft: "Airbus A330-300",
    totalSeats: 297,
    bookedSeats: 210,
    price: 299,
    status: "scheduled",
    date: "2025-10-15",
  },
  {
    id: "2",
    flightNumber: "UR425",
    airline: "Uganda Airlines",
    origin: "Hoima International Airport",
    destination: "Kisumu International Airport",
    departureTime: "14:15",
    arrivalTime: "15:45",
    aircraft: "Bombardier CRJ-900LR",
    totalSeats: 90,
    bookedSeats: 65,
    price: 189,
    status: "scheduled",
    date: "2025-10-10",
  },
  {
    id: "3",
    flightNumber: "QTR1384",
    airline: "Qatar Airways",
    origin: "QTR",
    destination: "EBB",
    departureTime: "19:30",
    arrivalTime: "22:15",
    aircraft: "Boeing 777",
    totalSeats: 300,
    bookedSeats: 145,
    price: 349,
    status: "scheduled",
    date: "2025-11-15",
  },
  {
    id: "4",
    flightNumber: "RWD422",
    airline: "RwandAir",
    origin: "KGL",
    destination: "EBB",
    departureTime: "12:00",
    arrivalTime: "13:20",
    aircraft: "Boeing 737",
    totalSeats: 175,
    bookedSeats: 145,
    price: 129,
    status: "scheduled",
    date: "2025-11-23",
  },
]

export const mockRoutes: Route[] = [
  {
    id: "1",
    origin: "QTR",
    destination: "EBB",
    distance: 2160,
    averageLoadFactor: 82,
    frequency: 14,
    seasonality: "high",
    profitability: 85,
  },
  {
    id: "2",
    origin: "EBB",
    destination: "NBO",
    distance: 325,
    averageLoadFactor: 65,
    frequency: 21,
    seasonality: "high",
    profitability: 72,
  },
  {
    id: "3",
    origin: "JNB",
    destination: "EBB",
    distance: 2970,
    averageLoadFactor: 65,
    frequency: 10,
    seasonality: "low",
    profitability: 45,
  },
]

export const mockSeatUtilization: SeatUtilization[] = [
  {
    flightId: "1",
    predictedOccupancy: 34,
    confidence: 85,
    emptySeats: 60,
    riskLevel: "medium",
    recommendations: ["Offer community pricing", "Consider route timing adjustment"],
  },
  {
    flightId: "2",
    predictedOccupancy: 59,
    confidence: 78,
    emptySeats: 61,
    riskLevel: "high",
    recommendations: ["Implement dynamic pricing", "Target local community outreach"],
  },
  {
    flightId: "3",
    predictedOccupancy: 48,
    confidence: 92,
    emptySeats: 155,
    riskLevel: "high",
    recommendations: ["Consider flight consolidation", "Aggressive community pricing"],
  },
]

export const mockPricingRecommendations: PricingRecommendation[] = [
  {
    flightId: "1",
    currentPrice: 390,
    recommendedPrice: 199,
    discount: 33,
    targetAudience: "community",
    urgency: "medium",
  },
  {
    flightId: "2",
    currentPrice: 189,
    recommendedPrice: 129,
    discount: 32,
    targetAudience: "community",
    urgency: "high",
  },
  {
    flightId: "3",
    currentPrice: 349,
    recommendedPrice: 179,
    discount: 49,
    targetAudience: "community",
    urgency: "high",
  },
]

export const mockAnalytics: Analytics = {
  totalFlights: 156,
  averageLoadFactor: 68,
  emptySeatsToday: 2847,
  revenueOpportunity: 284700,
  routesAtRisk: 12,
  communityBookings: 89,
}
